### ISSUE TITLE
Unhandled term: {"ctor":"Cse"

### ISSUE THREAD

**Issue by bukzor** [HigherOrderCO/Kind#100]
I wrote a program so bad that it makes Formality fail to give an error message.

```
$ head head.fm
head.splitc(c: Char, xs: List(Char)): List(List(Char))
    case xs:
    | nil => List.nil<List(Char)>;
    | cons => if U16.eql(xs.head, c)
        then List.cons<>(c, head.splitc(c, xs.tail))
        else head.splitc(c, xs.tail);

head.splitc_example3 :  _
  head.splitc('x', ['a', 'x', 'b'])



$ fmio head.splitc_example3
(node:4113) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'comp' of undefined
    at check (/home/bukzor/repo/Formality/node_modules/formality-lang/FormalityComp.js:273:27)
    at check (/home/bukzor/repo/Formality/node_modules/formality-lang/FormalityComp.js:243:24)
    at check (/home/bukzor/repo/Formality/node_modules/formality-lang/FormalityComp.js:243:24)
    at Object.core_to_comp (/home/bukzor/repo/Formality/node_modules/formality-lang/FormalityComp.js:283:23)
    at Object.compile (/home/bukzor/repo/Formality/node_modules/formality-lang/FormalityToJS.js:642:32)
    at Object._io_ (/home/bukzor/repo/Formality/node_modules/formality-lang/bin/lib.js:208:18)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4113) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4113) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by bukzor** [comment]
PR #104 Gives this failure a better error message:

```
Unhandled term: {"ctor":"Cse","name":"xs#J","func":{"ctor":"Loc","from":60,"upto":68,"expr":
{"ctor":"Ann","done":true,"expr":{"ctor":"Var","indx":"xs#2"},"type":{"ctor":"Ref","name":"String"}}},
"info":[{"ctor":"Ext","head":["xs",{"ctor":"Ann","done":true,"expr":{"ctor":"Var","indx":"xs#2"},"type":
{"ctor":"Ref","name":"String"}}],"tail":{"ctor":"Ext","head":["sep",{"ctor":"Ann","done":true,"expr":
{"ctor":"Var","indx":"sep#1"},"type":{"ctor":"Ref","name":"String"}}],"tail":{"ctor":"Nil","size":0},
"size":1},"size":2},[null,null,null]]}
```
