### ISSUE TITLE
Compiler doesn't support erasing functions

### ISSUE THREAD

**Issue by elmattic** [HigherOrderCO/Kind#163]
Here's a reproductible sample if we want to support erasing functions or just warn the user that he's trying to use, at runtime, a variable that is erased (here `size` in the `Nat.add.zero_right(size)` expression:

```
Nat.add.succ_other(a: Nat, b: Nat): (a + Nat.succ(b)) == (Nat.succ(a) + b)
  case a {
    zero: refl
    succ:
      apply(Nat.succ, Nat.add.succ_other(a.pred, b))
  }!

Word.mkinv.go<size: Nat, sizei: Nat>(a: Word(size), acc: Word(sizei)): Word(Nat.add(size, sizei))
  case a {
    e: acc
    i:
      let x = Word.mkinv.go<a.size, Nat.succ(sizei)>(a.pred, Word.i<sizei>(acc))
      x :: rewrite t in Word(t) with Nat.add.succ_other(a.size, sizei),
    o:
      let x = Word.mkinv.go<a.size, Nat.succ(sizei)>(a.pred, Word.i<sizei>(acc))
      x :: rewrite t in Word(t) with Nat.add.succ_other(a.size, sizei),
  }: Word(Nat.add(a.size, sizei))

Word.mkinv<size: Nat>(a: Word(size)): Word(size)
  let x = Word.mkinv.go<size, 0>(a, Word.e)
  x :: rewrite t in Word(t) with Nat.add.zero_right(size)

Main: IO<Unit>
  do IO {
    let x = 255
    let a = Word.from_bits(8, Nat.to_bits(x))
    let c = Word.mkinv!(a)

    IO.print(Nat.show(Word.to_nat!(c)))
  }
```

This code typechecks but fails at runtime with:

```
base$ kind Main --run
Compilation error.
ReferenceError: _a$size$5 is not defined
    at Word$mkinv$go$ (/Users/elmattic/Code/Kind/base/.kind.tmp.js:126:365)
    at Word$mkinv$go$ (/Users/elmattic/Code/Kind/base/.kind.tmp.js:126:284)
    at Word$mkinv$go$ (/Users/elmattic/Code/Kind/base/.kind.tmp.js:126:284)
    at Word$mkinv$go$ (/Users/elmattic/Code/Kind/base/.kind.tmp.js:126:284)
    at Word$mkinv$go$ (/Users/elmattic/Code/Kind/base/.kind.tmp.js:126:284)
    at Word$mkinv$go$ (/Users/elmattic/Code/Kind/base/.kind.tmp.js:126:284)
    at Word$mkinv$go$ (/Users/elmattic/Code/Kind/base/.kind.tmp.js:126:284)
    at Word$mkinv$go$ (/Users/elmattic/Code/Kind/base/.kind.tmp.js:126:284)
    at Word$mkinv$ (/Users/elmattic/Code/Kind/base/.kind.tmp.js:130:41)
    at /Users/elmattic/Code/Kind/base/.kind.tmp.js:197:100
```

**Comment by VictorTaelin** [comment]
This should now work because `rewrite` specifically is now "optimized" to ignore its argument. But I can't make sense of how erasing functions should work. For example, if you erase the function in `(λt. λf. t)(1)(2)`, what should it return?

**Comment by algebraic-dev** [comment]
Too old
