### ISSUE TITLE
kind --run results in js compilation error when a constructor is named "in"

### ISSUE THREAD

**Issue by wkolowski** [HigherOrderCO/Kind#265]
### Describe the bug
Take a look at the following code (bonus points for guessing what it's intended to do).

```FM(A : Type) : Type
  self(P : FM(A) -> Type) ->
  (in : (a : A) -> P(in(A, a))) ->
  (id  : P(id(A))) ->
  (op : (x : FM(A)) -> (y : FM(A)) -> P(op(A, x, y))) ->
  P(self)

in(A : Type)(a : A) : FM(A)
  (P, in, id, op) in(a)

id(A : Type) : FM(A)
  (P, in, id, op) id

op(A : Type, x : FM(A), y : FM(A)) : FM(A)
  case x {
    in: case y {
      in: op(A, x, y)
      id: x
      op: op(A, x, y)
    }
    id: y
    op: case y {
      in: op(A, x, y)
      id: x
      op: op(A, x, y)
    }      
  }

idleft : FM(Bool)
  op(Bool, id(Bool), in(Bool, true))
```

### To Reproduce
When I issue the command `kind idleft --run`, I get this error message:

```
Compilation error.
/home/wk/Code/Kind/Kind/base/.kind.tmp.js:11
  const in = x0=>x1=>x2=>x3=>x4=>x5=>in$(x0,x1,x2,x3,x4,x5);
        ^^

SyntaxError: Unexpected token 'in'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /nix/store/ykvmnw1xdcinhwfn23949xvq4l7jzb09-node_kind-lang-1.0.37/lib/node_modules/kind-lang/src/main.js:159:7
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

What happens is that the constructor named `in` was also named `in` in the output js code, but it's a reserved keyword here so it breaks down.

### Expected behavior
No error.

### Environment (please complete the following information):
 - OS: NixOS
 - Kind version: 1.0.37
 
I'm sorry for using such an outdated version; I couldn't manage to install the newest one on NixOS using node2nix - maybe I'll post an issue describing that.

**Comment by rigille** [comment]
Is it a free monoid? That's cool. Unfortunately the problem is still there as of `1.0.90`, the fix is to avoid js reserved names in `FmcToJs`.

**Comment by algebraic-dev** [comment]
Closed because the repository now only contains the code for the Kind2 language.
