### ISSUE TITLE
ReferenceError: subst_name is not defined

### ISSUE THREAD

**Issue by LoPoHa** [HigherOrderCO/Kind#37]
OS: Nixos unstable
Formality: 0.3.150

---

Running/typechecking the following code:

```
test : Word
  get [a ~ b] = temp
  a

temp : [: Word ~ Word]
  [1 ~ 2]
```

results in the following error:
```
ReferenceError: subst_name is not defined
    at typecheck (/nix/store/zhqg3jyrxfpp17jmgbgxkpfzqvvg6vpl-node_formality-lang-0.3.150/lib/node_modules/formality-lang/src/fm-core.js:1093:33)
    at typecheck (/nix/store/zhqg3jyrxfpp17jmgbgxkpfzqvvg6vpl-node_formality-lang-0.3.150/lib/node_modules/formality-lang/src/fm-core.js:1126:38)
    at typecheck (/nix/store/zhqg3jyrxfpp17jmgbgxkpfzqvvg6vpl-node_formality-lang-0.3.150/lib/node_modules/formality-lang/src/fm-core.js:1208:24)
    at typecheck (/nix/store/zhqg3jyrxfpp17jmgbgxkpfzqvvg6vpl-node_formality-lang-0.3.150/lib/node_modules/formality-lang/src/fm-lang.js:2518:10)
    at Object.run (/nix/store/zhqg3jyrxfpp17jmgbgxkpfzqvvg6vpl-node_formality-lang-0.3.150/lib/node_modules/formality-lang/src/fm-lang.js:2531:24)
    at /nix/store/zhqg3jyrxfpp17jmgbgxkpfzqvvg6vpl-node_formality-lang-0.3.150/lib/node_modules/formality-lang/src/main.js:190:34
```

running it normally results in `2` and with `-o` in `{x0} => x0`

---

Question:
How would i get the first value in `test` to do some computation with it?
If i change
```
 get [a ~ b] = temp
```
to 
```
 get [a, b] = temp
```
i get
```
[ERROR]
Mismatched erasure.
- When checking get [a,b] = temp; b
```

**Comment by VictorTaelin** [comment]
`get [a ~ b] = temp` is right. You can also use `fst~(temp)`.
